import type { CharacterSpec } from './character.js';
import type { MashinalRecord } from './types.js';

function g(
  body: number,
  hair: number,
  eyes: number,
  mouth: number,
  clothes: number,
  accessory: number,
  palette: number,
): CharacterSpec {
  return { genes: { body, hair, eyes, mouth, clothes, accessory, palette } };
}

const now = 0;

/** Primordial starter cast — original Mashinals pixel sprites. */
export const STARTERS: MashinalRecord[] = [
  {
    id: 'starter_spark',
    name: 'Spark',
    caption: 'Tiny lightning with big opinions.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:spark',
    spec: g(0, 1, 2, 1, 1, 1, 0),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_tide',
    name: 'Tide',
    caption: 'Saltwater softie who surfs every mood.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:tide',
    spec: g(1, 2, 1, 0, 2, 0, 1),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_pebble',
    name: 'Pebble',
    caption: 'Rock-solid vibes, surprisingly soft landing.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:pebble',
    spec: g(2, 3, 0, 3, 3, 0, 2),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_gust',
    name: 'Gust',
    caption: 'Whispers through timelines and hairdos.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:gust',
    spec: g(1, 4, 3, 2, 0, 2, 3),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_pixel',
    name: 'Pixel',
    caption: '8-bit heart in a 4K world.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:pixel',
    spec: g(0, 5, 4, 4, 4, 3, 4),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_meme',
    name: 'Meme',
    caption: 'Born to be remixed. Destined to be inscribed.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:meme',
    spec: g(0, 0, 2, 4, 1, 4, 5),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_heart',
    name: 'Heart',
    caption: 'Softcore chaos engine. Loves everyone loudly.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:heart',
    spec: g(1, 1, 0, 1, 0, 2, 6),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
  {
    id: 'starter_glitch',
    name: 'Glitch',
    caption: 'Error ✨ aesthetic ✨ forever.',
    generation: 0,
    parentAId: null,
    parentBId: null,
    parentAName: null,
    parentBName: null,
    parentAOrigin: null,
    parentBOrigin: null,
    recipeKey: 'starter:glitch',
    spec: g(3, 5, 4, 4, 4, 4, 7),
    discoveredAt: now,
    origin: null,
    txid: null,
    demoOrigin: null,
    svgHash: null,
    isStarter: true,
    isDiscovery: true,
  },
];

export function getStarterById(id: string): MashinalRecord | undefined {
  return STARTERS.find((s) => s.id === id);
}
